// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD35dCKdJuBbsDsojBjqjYrqMuS68Ul7FE',
    appId: '1:90253014715:web:275e59bac6733299839b9e',
    messagingSenderId: '90253014715',
    projectId: 'aplicaciones-moviles-par-70aa6',
    authDomain: 'aplicaciones-moviles-par-70aa6.firebaseapp.com',
    storageBucket: 'aplicaciones-moviles-par-70aa6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD3wuMcQBM0vYAT04x2V1ERGNv4kmYeJc',
    appId: '1:90253014715:android:a4447428f70e45c6839b9e',
    messagingSenderId: '90253014715',
    projectId: 'aplicaciones-moviles-par-70aa6',
    storageBucket: 'aplicaciones-moviles-par-70aa6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcw2wVsk7vEOlEZipDDOM6lfrTlMHP3mw',
    appId: '1:90253014715:ios:ad37bc1a14f7a218839b9e',
    messagingSenderId: '90253014715',
    projectId: 'aplicaciones-moviles-par-70aa6',
    storageBucket: 'aplicaciones-moviles-par-70aa6.firebasestorage.app',
    iosBundleId: 'com.example.miprimerflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcw2wVsk7vEOlEZipDDOM6lfrTlMHP3mw',
    appId: '1:90253014715:ios:ad37bc1a14f7a218839b9e',
    messagingSenderId: '90253014715',
    projectId: 'aplicaciones-moviles-par-70aa6',
    storageBucket: 'aplicaciones-moviles-par-70aa6.firebasestorage.app',
    iosBundleId: 'com.example.miprimerflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD35dCKdJuBbsDsojBjqjYrqMuS68Ul7FE',
    appId: '1:90253014715:web:66f372d6599973c0839b9e',
    messagingSenderId: '90253014715',
    projectId: 'aplicaciones-moviles-par-70aa6',
    authDomain: 'aplicaciones-moviles-par-70aa6.firebaseapp.com',
    storageBucket: 'aplicaciones-moviles-par-70aa6.firebasestorage.app',
  );

}